name: Add Reviewers

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed  # for merge PR
      - synchronize
    branches:
      - 'develop'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: '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'
        reviewers: thanghuynh2608
        re-request-when-approved: true
        re-request-when-changes-requested: true
        debug-mode: false
