  on:
    pull_request_target:
      types:
        - opened
        - reopened
        - closed  # for merge PR
        - synchronize
      branches:
        - 'develop'
        - 'master'
    workflow_dispatch:

  env:
    AWS_REGION: ${{ github.base_ref == 'develop' && 'US-east-1' || 'US-east-2' }}

  jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - run: echo $AWS_REGION
          - uses: actions/checkout@v4
          
          - uses: actions/setup-java@v3
            with:
              distribution: oracle
              java-version: 17
              
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2
          
          - name: Execute Gradle build
            run: gradle build

          - name: List dir
            run: ls
